name: Build and test

on:
  pull_request:

jobs:
  docker:
    name: Docker tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ github.repository }}:test

      - name: Test Docker image
        run: docker run --rm --user root:root --entrypoint bash ${{ github.repository }}:test -c 'pip install pytest-asyncio && pytest --pyargs gcn_classic_to_kafka'

  python:
    name: Python tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1

      - name: Install poetry
        run: pip install poetry

      - name: Install package
        run: poetry install

      - name: Run unit tests
        run: poetry run pytest . --cov --cov-report=xml

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
